'use strict';

/**
 * Converts the structured Claude response into Slack Block Kit blocks.
 * Section 1 (agentTroubleshooting) and Section 2 (customerEmailDraft) are
 * clearly separated so agents can quickly scan both.
 *
 * @param {object} response - Parsed JSON from Claude.
 * @returns {Array} Slack Block Kit blocks array.
 */
function formatSlackBlocks(response) {
  const { agentTroubleshooting: at, customerEmailDraft: cd } = response;
  const blocks = [];

  // ── Header ──────────────────────────────────────────────────────────────
  blocks.push({
    type: 'header',
    text: { type: 'plain_text', text: ':wrench: ServiceTitan Integrations Support', emoji: true },
  });

  blocks.push({ type: 'divider' });

  // ── Section 1: Agent Troubleshooting ────────────────────────────────────
  blocks.push({
    type: 'section',
    text: { type: 'mrkdwn', text: '*:lock: SECTION 1 — Agent Troubleshooting (Internal Only)*' },
  });

  blocks.push({
    type: 'section',
    text: { type: 'mrkdwn', text: `*Summary:* ${at.summary}` },
  });

  if (at.likelyCauses?.length) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Likely Causes:*\n${at.likelyCauses.map((c) => `• ${c}`).join('\n')}`,
      },
    });
  }

  if (at.verificationSteps?.length) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Verification Steps:*\n${at.verificationSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}`,
      },
    });
  }

  if (at.escalation) {
    const esc = at.escalation;
    const escText = esc.required
      ? `:rotating_light: *Escalation Required* → ${esc.team}\n_Reason: ${esc.reason}_`
      : ':white_check_mark: *No escalation required*';
    blocks.push({ type: 'section', text: { type: 'mrkdwn', text: escText } });
  }

  if (at.kbArticles?.length) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*KB Articles:*\n${at.kbArticles.map((kb) => `• ${kb}`).join('\n')}`,
      },
    });
  }

  if (at.internalNotes) {
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `*Internal Notes:* ${at.internalNotes}` },
    });
  }

  blocks.push({ type: 'divider' });

  // ── Section 2: Customer Email Draft ─────────────────────────────────────
  blocks.push({
    type: 'section',
    text: { type: 'mrkdwn', text: '*:email: SECTION 2 — Customer Email Draft*' },
  });

  const emailBody = [
    `*Subject:* ${cd.subject}`,
    '',
    cd.greeting,
    '',
    cd.body,
    '',
    cd.closing,
  ].join('\n');

  blocks.push({
    type: 'section',
    text: { type: 'mrkdwn', text: emailBody },
  });

  blocks.push({ type: 'divider' });

  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: ':robot_face: Generated by ServiceTitan Integrations Support Assistant · Internal use only',
      },
    ],
  });

  return blocks;
}

module.exports = { formatSlackBlocks };
