'use strict';

/**
 * Converts the new markdown-based Claude response into Slack Block Kit blocks.
 *
 * Expected input shape:
 * {
 *   agent_troubleshooting_markdown: string,
 *   customer_email_markdown: string,
 *   metadata: { confidence, estimated_time_minutes, kb_links, escalation_needed, escalation_target }
 * }
 *
 * @param {object} response - Parsed JSON from Claude.
 * @returns {Array} Slack Block Kit blocks array.
 */
function formatSlackBlocks(response) {
  const { agent_troubleshooting_markdown, customer_email_markdown, metadata } = response;
  const blocks = [];

  // ── Header ──────────────────────────────────────────────────────────────
  blocks.push({
    type: 'header',
    text: { type: 'plain_text', text: ':wrench: ServiceTitan Integrations Support', emoji: true },
  });

  blocks.push({ type: 'divider' });

  // ── Section 1: Agent Troubleshooting (markdown from Claude) ─────────────
  blocks.push({
    type: 'section',
    text: { type: 'mrkdwn', text: '*:lock: INTERNAL — Agent Troubleshooting*' },
  });

  // Slack blocks have a 3000-char limit per text field. Split if needed.
  for (const chunk of splitMarkdown(agent_troubleshooting_markdown, 2900)) {
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: chunk },
    });
  }

  blocks.push({ type: 'divider' });

  // ── Section 2: Customer Email Draft (markdown from Claude) ──────────────
  blocks.push({
    type: 'section',
    text: { type: 'mrkdwn', text: '*:email: Customer Email Draft*' },
  });

  for (const chunk of splitMarkdown(customer_email_markdown, 2900)) {
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: chunk },
    });
  }

  blocks.push({ type: 'divider' });

  // ── Metadata footer ────────────────────────────────────────────────────
  const metaParts = [];
  if (metadata) {
    metaParts.push(`Confidence: *${metadata.confidence || 'unknown'}*`);
    if (metadata.estimated_time_minutes != null) {
      metaParts.push(`Est. time: *${metadata.estimated_time_minutes} min*`);
    }
    if (metadata.escalation_needed) {
      metaParts.push(`:rotating_light: Escalation → *${metadata.escalation_target}*`);
    }
  }

  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: [
          ':robot_face: Generated by ServiceTitan Integrations Support Assistant',
          ...metaParts,
        ].join('  |  '),
      },
    ],
  });

  return blocks;
}

/**
 * Splits a markdown string into chunks that fit within Slack's text field limit.
 * Splits on double-newlines (paragraph boundaries) to keep content readable.
 *
 * @param {string} text - The full markdown text.
 * @param {number} maxLen - Maximum character length per chunk.
 * @returns {string[]} Array of chunks.
 */
function splitMarkdown(text, maxLen) {
  if (!text || text.length <= maxLen) return [text || ''];

  const paragraphs = text.split(/\n\n/);
  const chunks = [];
  let current = '';

  for (const para of paragraphs) {
    const candidate = current ? `${current}\n\n${para}` : para;
    if (candidate.length > maxLen && current) {
      chunks.push(current);
      current = para;
    } else {
      current = candidate;
    }
  }
  if (current) chunks.push(current);

  return chunks;
}

module.exports = { formatSlackBlocks };
